{{- if and .Values.mcpServer.enabled .Values.mcpServer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mcall-operator.fullname" . }}-mcp-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mcall-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
  {{- with .Values.mcpServer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mcpServer.ingress.className }}
  ingressClassName: {{ .Values.mcpServer.ingress.className }}
  {{- end }}
  {{- if .Values.mcpServer.ingress.tls }}
  tls:
    {{- range .Values.mcpServer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mcpServer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mcall-operator.fullname" $ }}-mcp-server
                port:
                  number: {{ $.Values.mcpServer.service.port }}
          {{- end }}
    {{- end }}
{{- end }}

