{{- if .Values.mcpServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcall-operator.fullname" . }}-mcp-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mcall-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  replicas: {{ .Values.mcpServer.replicas }}
  selector:
    matchLabels:
      {{- include "mcall-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        {{- include "mcall-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      serviceAccountName: {{ include "mcall-operator.fullname" . }}-mcp-server
      {{- with .Values.mcpServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mcp-server
        image: "{{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag }}"
        imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.mcpServer.service.targetPort }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.mcpServer.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: MCP_REQUIRE_AUTH
          value: {{ .Values.mcpServer.auth.enabled | quote }}
        {{- if .Values.mcpServer.auth.enabled }}
        - name: MCP_API_KEYS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mcpServer.auth.existingSecret | default "mcp-api-keys" }}
              key: api-keys
        {{- end }}
        {{- with .Values.mcpServer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.mcpServer.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.mcpServer.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.mcpServer.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.mcpServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

