package v1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// McallTaskSpec defines the desired state of McallTask
type McallTaskSpec struct {
	// Type of request (command, HTTP GET, HTTP POST)
	Type string `json:"type"`

	// Input command or URL to execute
	Input string `json:"input"`

	// Name identifier for this task
	Name string `json:"name,omitempty"`

	// Timeout in seconds
	Timeout int32 `json:"timeout,omitempty"`

	// Number of retries on failure
	RetryCount int32 `json:"retryCount,omitempty"`

	// Cron schedule for recurring tasks (optional)
	Schedule string `json:"schedule,omitempty"`

	// List of task names this task depends on
	Dependencies []string `json:"dependencies,omitempty"`

	// Environment variables for task execution
	Environment map[string]string `json:"environment,omitempty"`

	// Resource requirements for task execution
	Resources v1.ResourceRequirements `json:"resources,omitempty"`

	// HTTP response validation for GET/POST requests
	HttpValidation *HttpValidation `json:"httpValidation,omitempty"`

	// Command output validation for CMD requests
	OutputValidation *OutputValidation `json:"outputValidation,omitempty"`

	// Execution mode for multiple inputs (sequential/parallel)
	ExecutionMode string `json:"executionMode,omitempty"`

	// Fail fast on error - stop execution on first error (default: false)
	FailFast bool `json:"failFast,omitempty"`
}

// McallTaskStatus defines the observed state of McallTask
type McallTaskStatus struct {
	// Current phase of the task
	Phase McallTaskPhase `json:"phase"`

	// When the task started
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// When the task completed
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// Task execution result
	Result *McallTaskResult `json:"result,omitempty"`

	// Current retry count
	RetryCount int32 `json:"retryCount,omitempty"`

	// Last retry attempt time
	LastRetryTime *metav1.Time `json:"lastRetryTime,omitempty"`
}

// McallTaskResult represents the result of task execution
type McallTaskResult struct {
	// Task output
	Output string `json:"output,omitempty"`

	// Error code (0 for success, -1 for failure)
	ErrorCode string `json:"errorCode,omitempty"`

	// Error message if failed
	ErrorMessage string `json:"errorMessage,omitempty"`
}

// McallTaskPhase represents the phase of a task
type McallTaskPhase string

const (
	McallTaskPhasePending   McallTaskPhase = "Pending"
	McallTaskPhaseRunning   McallTaskPhase = "Running"
	McallTaskPhaseSucceeded McallTaskPhase = "Succeeded"
	McallTaskPhaseFailed    McallTaskPhase = "Failed"
	McallTaskPhaseSkipped   McallTaskPhase = "Skipped"
)

// Execution mode constants
const (
	ExecutionModeSequential = "sequential"
	ExecutionModeParallel   = "parallel"
)

const McallTaskFinalizer = "mcall.tz.io/finalizer"

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
//+kubebuilder:printcolumn:name="Type",type="string",JSONPath=".spec.type"
//+kubebuilder:printcolumn:name="Input",type="string",JSONPath=".spec.input"
//+kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// McallTask is the Schema for the mcalltasks API
type McallTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   McallTaskSpec   `json:"spec,omitempty"`
	Status McallTaskStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// McallTaskList contains a list of McallTask
type McallTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []McallTask `json:"items"`
}

func init() {
	SchemeBuilder.Register(&McallTask{}, &McallTaskList{})
}

// DeepCopyObject returns a generically typed copy of an object
func (in *McallTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McallTask.
func (in *McallTask) DeepCopy() *McallTask {
	if in == nil {
		return nil
	}
	out := new(McallTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McallTask) DeepCopyInto(out *McallTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McallTaskSpec.
func (in *McallTaskSpec) DeepCopy() *McallTaskSpec {
	if in == nil {
		return nil
	}
	out := new(McallTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McallTaskSpec) DeepCopyInto(out *McallTaskSpec) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McallTaskStatus.
func (in *McallTaskStatus) DeepCopy() *McallTaskStatus {
	if in == nil {
		return nil
	}
	out := new(McallTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McallTaskStatus) DeepCopyInto(out *McallTaskStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopyObject returns a generically typed copy of an object
func (in *McallTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McallTaskList.
func (in *McallTaskList) DeepCopy() *McallTaskList {
	if in == nil {
		return nil
	}
	out := new(McallTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McallTaskList) DeepCopyInto(out *McallTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]McallTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// HttpValidation defines HTTP response validation rules
type HttpValidation struct {
	// Expected HTTP status codes
	ExpectedStatusCodes []int `json:"expectedStatusCodes,omitempty"`

	// Expected response body content
	ExpectedResponseBody string `json:"expectedResponseBody,omitempty"`

	// How to match response body
	ResponseBodyMatch string `json:"responseBodyMatch,omitempty"`

	// Regex pattern for response body matching
	ResponseBodyPattern string `json:"responseBodyPattern,omitempty"`

	// Expected response headers
	ResponseHeaders map[string]string `json:"responseHeaders,omitempty"`

	// HTTP response timeout in seconds
	ResponseTimeout int32 `json:"responseTimeout,omitempty"`

	// Whether to follow redirects
	FollowRedirects bool `json:"followRedirects,omitempty"`

	// Maximum number of redirects to follow
	MaxRedirects int32 `json:"maxRedirects,omitempty"`
}

// OutputValidation defines command output validation rules
type OutputValidation struct {
	// Expected output content
	ExpectedOutput string `json:"expectedOutput,omitempty"`

	// How to match output content
	OutputMatch string `json:"outputMatch,omitempty"`

	// Regex pattern for output matching
	OutputPattern string `json:"outputPattern,omitempty"`

	// Success criteria for output validation
	SuccessCriteria string `json:"successCriteria,omitempty"`

	// Failure criteria for output validation
	FailureCriteria string `json:"failureCriteria,omitempty"`

	// Whether output matching is case sensitive
	CaseSensitive bool `json:"caseSensitive,omitempty"`

	// Whether to support multiline output
	Multiline bool `json:"multiline,omitempty"`

	// Expected number of output lines
	ExpectedLines int32 `json:"expectedLines,omitempty"`

	// Output timeout in seconds
	OutputTimeout int32 `json:"outputTimeout,omitempty"`

	// JSONPath expression for JSON validation
	JsonPath string `json:"jsonPath,omitempty"`

	// Expected JSON value at specified path
	ExpectedJsonValue string `json:"expectedJsonValue,omitempty"`

	// Expected output content that indicates failure
	ExpectedFailureOutput string `json:"expectedFailureOutput,omitempty"`
}
