{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcallworkflows.mcall.tz.io
  labels:
    app.kubernetes.io/name: mcall
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.environment.name | quote }}
    crd.version: v1
  annotations:
    mcall.tz.io/environment: {{ .Values.environment.name | quote }}
    mcall.tz.io/version: v1
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: mcall.tz.io
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tasks:
                type: array
                description: List of McallTask references in this workflow
                items:
                  type: object
                  required:
                  - name
                  - taskRef
                  properties:
                    name:
                      type: string
                      description: Name of the task in the workflow
                    taskRef:
                      type: object
                      required:
                      - name
                      properties:
                        name:
                          type: string
                          description: Name of the McallTask
                        namespace:
                          type: string
                          description: Namespace of the McallTask
                    dependencies:
                      type: array
                      description: List of task names this task depends on
                      items:
                        type: string
              schedule:
                type: string
                description: Cron schedule for workflow execution (optional)
                pattern: '^(\*|(\d+|\*/\d+)(,\d+)*) (\*|(\d+|\*/\d+)(,\d+)*) (\*|(\d+|\*/\d+)(,\d+)*) (\*|(\d+|\*/\d+)(,\d+)*) (\*|(\d+|\*/\d+)(,\d+)*)$'
              concurrency:
                type: integer
                description: Maximum number of concurrent task executions
                minimum: 1
                default: 1
              timeout:
                type: integer
                description: Overall workflow timeout in seconds
                minimum: 1
                default: 300
              retryPolicy:
                type: object
                description: Retry policy for the workflow
                properties:
                  maxRetries:
                    type: integer
                    description: Maximum number of retries
                    minimum: 0
                    default: 0
                  retryDelay:
                    type: integer
                    description: Delay between retries in seconds
                    minimum: 1
                    default: 30
                  backoffPolicy:
                    type: string
                    description: Backoff policy for retries
                    enum:
                    - linear
                    - exponential
                    default: linear
              environment:
                type: object
                description: Environment variables for all tasks in the workflow
                additionalProperties:
                  type: string
              resources:
                type: object
                description: Resource requirements for all tasks
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
          status:
            type: object
            properties:
              phase:
                type: string
                description: Current phase of workflow execution
                enum:
                - Pending
                - Running
                - Succeeded
                - Failed
                default: Pending
              startTime:
                type: string
                format: date-time
                description: When the workflow started
              completionTime:
                type: string
                format: date-time
                description: When the workflow completed
              taskStatuses:
                type: array
                description: Status of individual tasks
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Name of the task
                    phase:
                      type: string
                      description: Current phase of the task
                      enum:
                      - Pending
                      - Running
                      - Succeeded
                      - Failed
                      - Skipped
                    startTime:
                      type: string
                      format: date-time
                      description: When the task started
                    completionTime:
                      type: string
                      format: date-time
                      description: When the task completed
                    message:
                      type: string
                      description: Human-readable message about the task status
                    reason:
                      type: string
                      description: Brief reason for the current status
              message:
                type: string
                description: Human-readable message about the workflow status
              reason:
                type: string
                description: Brief reason for the current status
              retryCount:
                type: integer
                description: Number of times the workflow has been retried
              lastRetryTime:
                type: string
                format: date-time
                description: Time of the last retry
              lastRunTime:
                type: string
                format: date-time
                description: Time when the workflow was last executed
  names:
    kind: McallWorkflow
    plural: mcallworkflows
    singular: mcallworkflow
    shortNames:
    - mwf
    - mw
  scope: Namespaced
{{- end }}
