# Development environment values
# This file can be committed to Git safely

environment:
  name: "dev"
  suffix: "-dev"

namespace:
  name: "mcall-dev"
  create: true

controller:
  replicas: 1
  reconcileInterval: 5
  taskTimeout: 5

mcpServer:
  enabled: true
  replicas: 1
  
  # Image tag is set by Jenkins via --set mcpServer.image.tag="${BUILD_NUMBER}"
  # Do not hardcode tag here
  
  auth:
    enabled: true  # Enable auth for development
    existingSecret: "mcp-api-keys"
    apiKeys: ""  # Use existing secret
  
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: mcp-dev.drillquiz.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mcp-server-dev-tls
        hosts:
          - mcp-dev.drillquiz.com
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
