# Staging/System environment values
# For mcall-system namespace

environment:
  name: "system"
  suffix: ""

namespace:
  name: "mcall-system"
  create: true

controller:
  replicas: 2
  reconcileInterval: 5
  taskTimeout: 5

mcpServer:
  enabled: true
  replicas: 2
  
  auth:
    enabled: true  # Enable authentication
    existingSecret: "mcp-api-keys"  # Use pre-created Secret
    apiKeys: ""  # DO NOT set keys here
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: mcp-dev.drillquiz.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mcp-server-staging-tls
        hosts:
          - mcp-dev.drillquiz.com
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  env:
    NODE_ENV: production
    DEFAULT_NAMESPACE: mcall-system
    SERVER_MODE: http
