# Development environment values
# This file can be committed to Git safely

environment:
  name: "dev"
  suffix: "-dev"

namespace:
  name: "mcall-dev"
  create: true

controller:
  replicas: 1
  reconcileInterval: 5
  taskTimeout: 5

mcpServer:
  enabled: true
  replicas: 1
  
  auth:
    enabled: false  # Disable auth for local development
    existingSecret: ""
    apiKeys: ""  # No keys needed when auth is disabled
  
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: mcp-dev.drillquiz.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mcp-server-dev-tls
        hosts:
          - mcp-dev.drillquiz.com
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
