apiVersion: mcall.tz.io/v1
kind: McallTask
metadata:
  name: jenkins-build-trigger-template
  namespace: mcall-dev
spec:
  type: mcp-client
  input: ""
  timeout: 60
  retryCount: 2
  mcpConfig:
    serverUrl: "https://jenkins.drillquiz.com/mcp-server/mcp"
    toolName: "triggerBuild"
    arguments:
      jobFullName: "docker-test"
    auth:
      type: "basic"
      secretRef:
        name: jenkins-mcp-credentials
        namespace: mcall-dev
      usernameKey: "username"
      passwordKey: "token"
    headers:
      Accept: "text/event-stream, application/json"
    connectionTimeout: 30