apiVersion: mcall.tz.io/v1
kind: McallTask
metadata:
  name: jenkins-build-trigger-template
  namespace: mcall-dev
spec:
  input: ""
  type: mcp-client
  timeout: 60
  retryCount: 2
  mcpConfig:
    serverUrl: https://jenkins.drillquiz.com/mcp-server/mcp
    toolName: triggerBuild
    connectionTimeout: 30
    headers:
      Accept: "text/event-stream, application/json"
    auth:
      type: basic
      secretRef:
        name: jenkins-mcp-credentials
        namespace: mcall-dev
      usernameKey: username
      passwordKey: token
    arguments:
      jobFullName: docker-test

