apiVersion: mcall.tz.io/v1
kind: McallWorkflow
metadata:
  name: test-workflow
  namespace: mcall-dev
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  tasks:
    # Task 1: Simple echo command
    - name: echo-task
      taskRef:
        name: echo-template
        namespace: mcall-dev
    # Task 2: Sleep command (runs after echo-task)
    - name: sleep-task
      taskRef:
        name: sleep-template
        namespace: mcall-dev
      dependencies:
        - echo-task
---
apiVersion: mcall.tz.io/v1
kind: McallTask
metadata:
  name: echo-template
  namespace: mcall-dev
spec:
  type: cmd
  input: "echo Hello from test-workflow!"
  name: "echo-template"
  timeout: 30
  retryCount: 1
---
apiVersion: mcall.tz.io/v1
kind: McallTask
metadata:
  name: sleep-template
  namespace: mcall-dev
spec:
  type: cmd
  input: "sleep 2"
  name: "sleep-template"
  timeout: 30
  retryCount: 1
