apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcall-system

resources:
- rbac.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: mcall-operator
  app.kubernetes.io/component: mcp-server

